import smtplib
from email.message import EmailMessage
from LEETCODE_SESSION_TEMPLATE import *

# CONFIGURATION
# ---------------------------------------------------
EMAIL_ADDRESS = email_address
EMAIL_PASSWORD = APP_PASSWORD
TARGET_EMAIL = target_email
# ---------------------------------------------------

def send_daily_revision_email(questions):
    if not questions:
        print("⚠️ No questions to email.")
        return

    date1 = str(questions[0]['last_solved_timestamp']).split("T")[0]
    date2 = str(questions[1]['last_solved_timestamp']).split("T")[0]

    msg = EmailMessage()
    msg['Subject'] = f"Daily LeetCode: {questions[0]['title']} & {questions[1]['title']}"
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = TARGET_EMAIL

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto;">
        <h2 style="color: #ffa116; border-bottom: 2px solid #ffa116; padding-bottom: 10px;">
            LeetCode Spaced Repetition
        </h2>
        <p>Rise and grind! Here are two problems you haven't touched in a long time.</p>
        
        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0;">1. {questions[0]['title']}</h3>
            <div>
                <span style="background-color: #eee; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold;">
                    {questions[0]['difficulty']}
                </span>
                <span style="font-size: 12px; color: #666; margin-left: 10px;">
                    Last Solved: {date1}
                </span>
            </div>
            <br>
            <a href="{questions[0]['url']}" style="background-color: #2da44e; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;">
                Solve Now
            </a>
        </div>

        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h3 style="margin: 0 0 10px 0;">2. {questions[1]['title']}</h3>
            <div>
                <span style="background-color: #eee; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold;">
                    {questions[1]['difficulty']}
                </span>
                <span style="font-size: 12px; color: #666; margin-left: 10px;">
                    Last Solved: {date2}
                </span>
            </div>
            <br>
            <a href="{questions[1]['url']}" style="background-color: #2da44e; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block;">
                Solve Now
            </a>
        </div>
        
        <p style="font-size: 12px; color: #999; text-align: center;">
            Generated by your Python Automation Bot 🤖
        </p>
    </body>
    </html>
    """

    msg.add_alternative(html_content, subtype='html')

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            smtp.send_message(msg)
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")